### ISSUE TITLE
refactor: Remove `errorRedactor`

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/gaxios#626]
Simply does not work well with the open-ended `data` & `body` types and is pretty unmaintainable. Instead, customers should use a proper data loss prevention (DLP) product for this [[example](https://cloud.google.com/security/products/dlp) [[infotypes](https://cloud.google.com/sensitive-data-protection/docs/infotypes-reference#credentials_and_secrets)]].

It has been marked as an `@experimental` API and thus is not breaking if removed.

https://github.com/googleapis/gaxios/blob/56b1410a95db951a962cbafe257e8defc6f155b2/README.md?plain=1#L191-L204

https://github.com/googleapis/gaxios/blob/56b1410a95db951a962cbafe257e8defc6f155b2/src/common.ts#L248-L259

https://github.com/googleapis/gaxios/blob/56b1410a95db951a962cbafe257e8defc6f155b2/src/common.ts#L392-L489

An internal bug is blocking this feature request - await it's resolution first.

**Comment by udayarctempus** [comment]
Do you know when this get released?  We are getting the following error, seems related to this 

TypeError: Cannot read properties of undefined (reading 'config')
    at Object.defaultErrorRedactor [as errorRedactor] (/opt/tempus/code/node_modules/gaxios/build/src/common.js:160:14)
    at TransformOperationExecutor.transform (/opt/tempus/code/node_modules/class-transformer/cjs/TransformOperationExecutor.js:192:51)
    at TransformOperationExecutor.transform (/opt/tempus/code/node_modules/class-transformer/cjs/TransformOperationExecutor.js:291:43)
    at TransformOperationExecutor.transform (/opt/tempus/code/node_modules/class-transformer/cjs/TransformOperationExecutor.js:291:43)
    at TransformOperationExecutor.transform (/opt/tempus/code/node_modules/class-transformer/cjs/TransformOperationExecutor.js:291:43)
    at ClassTransformer.instanceToPlain (/opt/tempus/code/node_modules/class-transformer/cjs/ClassTransformer.js:13:25)
